### ISSUE TITLE
Build failing on MacOS with Python 3.12.1 at  ... Install numpy 1.24.4 failed

### ISSUE THREAD

**Issue by brianmcentire** [matin/garth#42]
MacOS Sonoma 14.2.1, using latest python 3.12.1 

make install looks good all the way until the step for numpy 1.24.4, that fails and then pandas cannot install:

ERRORS:
add numpy failed:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.11.2/libexec/lib/python3.12/site-packages/pdm/installers/synchronizers.py", line 286, in install_candidate
    self.manager.install(can)
  File "/opt/homebrew/Cellar/pdm/2.11.2/libexec/lib/python3.12/site-packages/pdm/installers/manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
                              ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.11.2/libexec/lib/python3.12/site-packages/pdm/models/candidates.py", line 418, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.11.2/libexec/lib/python3.12/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pdm-install-qifi5at5.log](https://github.com/matin/garth/files/13881556/pdm-install-qifi5at5.log)

**Comment by matin** [comment]
This appears to be more of a numpy issue than a garth issue.

That being said, do the following instead of `make install`:
```
pdm install --prod
pdm install -G testing,linting
```

That'll get you up and running without needing pandas.

Let me know if that works for you.

**Comment by matin** [comment]
@brianmcentire did that work for you?

**Comment by matin** [comment]
Considering this closed. Let me know if it's still an issue

**Comment by brianmcentire** [comment]
This worked, thank you! (And sorry about the slow response.)
